download:

  # 同时下载的图片数量
  # 建议根据网络情况设置为 3-5 之间
  threads: 3

  # 网页/图片下载失败后的重试次数
  # 重试可能会消耗配额，建议设置为 1
  retries: 1

  # 在retries指定的重试次数消耗完后图片仍然下载失败的情况下
  # 尝试使用 'Click here if the image fails loading' 链接重试
  # 使用这种方法重试会消耗较多的配额
  nlretry: true

  # 原图存在时是否下载原图
  # 下载原图会消耗大量配额，默认为 false
  # 该选项仅在登录账号后可以设置为 true ，否则程序会发出警告并直接退出
  original: false

  # 是否使用日文标题创建文件夹，为 false 时使用主标题
  # 有些非法字符会被过滤，所以创建的文件夹标题未必和网页上的一致
  jtitle: true

  # 是否保存图片下载失败的日志
  # 为 true 时，当Gallery中部分图片下载失败时，会在下载目录中创建 failures.json 文件保存日志
  # 下次在同一目录下载这个Gallery时会读取 failures.json 并仅下载上次下载失败的图片
  failuresLog: true

  # 用户代理字符串
  userAgent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36"

login:

  # 在浏览器登录后获取以下三个cookie字段的值并填入下方
  # 当以下三个字段都不为空时会自动登录并验证是否登录成功
  # 如果登录验证失败会发出警告并直接退出程序
  __cfduid: ""
  ipb_member_id: ""
  ipb_pass_hash: ""