download:

  # 同时下载的图片数量
  # 建议根据网络情况设置为 3-5 之间
  threads: 3

  # 未实现
  # 图片下载失败后的重试次数
  # 重试也会消耗配额，建议设置为 1
  retries: 1

  # 未实现
  # 原图存在时是否下载原图
  # 下载原图会消耗大量配额，所以默认为 false
  # 该选项仅在登录账号后有效
  original: false


login:

  # 未实现
  # 用户名和密码使用英文双引号包裹
  # 如果不登陆，英文双引号留空
  # 有两个特殊的英文符号 " 和 \ 需要使用 \ 转义

  # 用户名
  username: ""

  # 密码
  password: ""