download:

  # 同时下载的图片数量
  # 建议根据网络情况设置为 3-5 之间
  threads: 3

  # 网页/图片下载失败后的重试次数
  # 重试可能会消耗配额，建议设置为 1
  retries: 1

  # 在retries指定的重试次数消耗完后图片仍然下载失败的情况下
  # 尝试使用 'Click here if the image fails loading' 链接重试
  # 使用这种方法重试会消耗较多的配额
  nlretry: true

  # 未实现
  # 原图存在时是否下载原图
  # 下载原图会消耗大量配额，所以默认为 false
  # 该选项仅在登录账号后有效
  original: false

  # 是否使用日文标题创建文件夹，为 false 时使用主标题
  # 有些非法字符会被过滤，所以创建的文件夹标题未必和网页上的一致
  jtitle: true

  # 用户代理字符串
  userAgent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36"

login:

  # 未实现
  # 用户名和密码使用英文双引号包裹
  # 如果不登陆，英文双引号内留空
  # 有两个特殊的英文符号 " 和 \ 需要使用 \ 转义

  # 用户名
  username: ""

  # 密码
  password: ""